#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: C.PSG1218

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Build Padavan"
        required: true
        default: "build"
  #release:
  # types: [created]
  push:
    tags:
      - "v*"
  #  branches:
  #    - master
  #  schedule:
  #    - cron: 0 8 * * 5
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
          token: ${{ secrets.GITHUB_TOKEN }}
        run: |
         echo "###########################"
           pwd
           #
           sudo mv padavan /opt/
           cd /opt/padavan
           echo "sudo ls -l"
           pwd
           sudo ls -l
           echo "###########################"
           #
          sudo apt-get update
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
      - name: Clone source code
        run: |
          git clone -b custom --depth=1 https://github.com/yh793/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh
          mkdir -p /opt/images/
          
      - name: Recovery bin files download from remote
        run: |
          cd /opt/padavan/PSG1218/
          sh install_Setconfig.sh
          #
          cd /opt/padavan/Theme/
          sh install_Theme.sh
          
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDHH
          utcOffset: "+08:00"
      - name: Build Firmware
        env:
          TNAME: PSG1218
        run: |
          cd /opt/rt-n56u/trunk
          if [ ! -f configs/templates/$TNAME.config ] ; then
          echo "configs/templates/$TNAME.config not found "
          exit 1
          fi
          cp -f configs/templates/$TNAME.config .config

          sudo ./clear_tree
          sudo ./build_firmware_modify $TNAME 0
          sudo mv -f images/*.trx /opt/images/${TNAME}_Hanwckf_${{ steps.current-time.outputs.formattedTime }}.trx
          echo "FNAME=$TNAME" >> $GITHUB_ENV

      - name: Organize files
        id: organize
        run: |
          echo "::set-output name=status::success"
      - name: Upload packages - push to artifact file
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success'
        with:
          name: Padavan-packages
          path: /opt/images
