#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: C.PSG1218

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Build Padavan"
        required: true
        default: "build"
  # release:
  #   types: [published]
  push:
    tags:
      - "v*"
  #  branches:
  #    - master
  #  schedule:
  #    - cron: 0 8 * * 5
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v3
      #- uses: hendrikmuhs/ccache-action@v1.2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.6'
      #- uses: actions/cache@v3
      #  with:
      #    path: |
      #      ~/.cache/go-build
      #      ~/go/pkg/mod
      #    key: ${{ runner.os }}-go-v1
      #    restore-keys: |
      #      ${{ runner.os }}-go-
        env:
          token: ${{ secrets.R_TOKEN }}
      - name: Prepare
        run: |
         echo "###########################"
          pwd
          #
          sudo mv padavan /opt/
          cd /opt/padavan
          echo "sudo ls -l"
          pwd
          sudo ls -l
          echo "###########################"
          #
          sudo apt-get update
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
          # https://github.com/actions/setup-go/issues/107
          echo "${GOROOT}/bin" >> $GITHUB_PATH
      - name: Clone source code
        run: |
          git clone -b chongshengB --depth=1 https://github.com/Yh793/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          curl -O -L  https://github.com/Yh793/Padavan-build/raw/master/mipsel-linux-uclibc.tar.xz
          mkdir -p toolchain-3.4.x
          tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
          #sh dl_toolchain.sh
          mkdir -p /opt/images/
      - name: adapt project
        run: |
          cd /opt/rt-n56u/trunk/user/adguardhome
          sed -i "s#https://cdn.jsdelivr.net/gh/chongshengB/rt-n56u/trunk/user/adguardhome/AdGuardHome#https://cdn.jsdelivr.net/gh/Yh793/Padavan-build/adg/AdGuardHome#g" ./adguardhome.sh
          cd /opt/rt-n56u/trunk/tools
          sed -i '34,40s/^/#/' ./Makefile
          cd /opt/rt-n56u/trunk/user/rc
          sed -i '/DNS_RELAY_CACHE_MAX/d' ./services_ex.c

      - name: Recovery bin files download from remote
        run: |
          cd /opt/padavan/PSG1218/
          sh install_Setconfig.sh
          #
          cd /opt/padavan/Theme/
          sh install_Theme.sh

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YY.MMDDHH
          utcOffset: "+08:00"

      - name: Build Firmware
        env:
          TNAME: PSG1218 #PSG1218 K2P-5.0 K2P K2P_nano K2P_nano-5.0 PSG1208 PSG1218_nano
        run: |
          cd /opt/rt-n56u/trunk
          if [ ! -f configs/templates/$TNAME.config ] ; then
          echo "configs/templates/$TNAME.config not found "
          exit 1
          fi
          cp -f configs/templates/$TNAME.config .config
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
          ################################################################################################
          #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
          ################################################################################################
          sed -i '/CONFIG_FIRMWARE_WIFI2_DRIVER=3.0/d' .config
          sed -i '/CONFIG_FIRMWARE_ENABLE_SWAP/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_HTTPS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #删除配置项SOFTETHERVPN
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #删除配置项SOFTETHERVPN
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #删除配置项SOFTETHERVPN
          sed -i '/CONFIG_FIRMWARE_WEBUI_HIDE_VPN/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
          sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
          sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项adbyby plus+
          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项adbyby plus+
          sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项adbyby plus+
          sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项阿里DDNS
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_KUMASOCKS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_MICROSOCKS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SFE/d' .config #删除配置项SFE加速
          #校园网相关
          sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
          sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
          #校园网相关
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
          ######################################################################
          #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
          ######################################################################        
          #2.4G 驱动选择
          ### 2.7 = MT7620 v2.7.2.0
          ### 3.0 = MT7620 v3.0.4.0
          echo "CONFIG_FIRMWARE_WIFI2_DRIVER=3.0" >> .config
          #
          ##启用交换文件/分区支持。约 0.05MB
          echo "CONFIG_FIRMWARE_ENABLE_SWAP=y" >> .config
          #
          ##包含 HTTPS 支持。openssl 约 1.2MB
          echo "CONFIG_FIRMWARE_INCLUDE_HTTPS=y" >> .config
          #
          ## iperf3测速软件
          echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=y" >> .config
          #
          ## MTR
          echo "CONFIG_FIRMWARE_INCLUDE_MTR=y" >> .config
          #
          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config #SOFTETHERVPN
          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config #SOFTETHERVPN
          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config #SOFTETHERVPN
          echo "CONFIG_FIRMWARE_WEBUI_HIDE_VPN=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SFE=n" >> .config #集成SFE加速
          #
          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
          echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
          echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
          echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfs混淆插件
          echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
          echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=n" >> .config #socks5
          #
          echo "CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_MICROSOCKS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #可以不集成
          echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
          echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
          #
          echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #内网穿透FRPC
          echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
          #
          echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
          echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
          #
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config #smartdns
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=y" >> .config #smartdns二进制文件
          echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
          #
          echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #阿里DDNS
          echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
          #       
          echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务
          echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
          #     
          echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #网易云解锁
          echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #网易云解锁GO版本执行文件（4M多）注意固件超大小,不集成会自动下载
          #校园网相关
          echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
          echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
          echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config
          #校园网相关
          #########################################################################################
          #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
          #格式如下：
          #sed -i '/自定义项/d' .config
          #echo "自定义项=y" >> .config
          #########################################################################################
          sudo ./clear_tree
          sudo ./build_firmware_modify $TNAME 0
          sudo mv -f images/*.trx /opt/images/${TNAME}_ChongshengB_${{ steps.current-time.outputs.formattedTime }}.trx
          echo "FNAME=$TNAME" >> $GITHUB_ENV
          echo "BUILDDONE=success" >> $GITHUB_ENV
          
      - name: Upload packages - push to artifact file
        uses: actions/upload-artifact@main
        if: env.BUILDDONE == 'success'
        with:
          name: C.PSG1218-Padavan-packages
          path: /opt/images
